### ISSUE TITLE
Review: The FavoriteCollection

### ISSUE THREAD

**Issue by cammoore** [cammoore/campus-cravings#2]
## Overview

For our first review, we're going to take a look at the FavoriteCollection. 

## Review Branch

review-2

## File to review

* [Favorite.js](https://github.com/cammoore/campus-cravings/blob/review-2/app/imports/api/favorite/Favorite.js)

## Checklists

(Please edit the following list if necessary to indicate the actual checklists to be used.)

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)

## Due date
Tuesday, January 26th at 12 pm. We'll meet by teams.

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by jackiewong99** [comment]
Line 8, 10, 12: Comments can be removed

**Comment by micgainey** [comment]
METEOR-01: insecure package still added.
METEOR-02: Add the mdg:validated-method package. Still missing.

**Comment by vrabang** [comment]
Lines 9, 11, and 13 are kinda redundant

**Comment by sophiaelizecruz** [comment]
Arch-01: Possible camel casing

**Comment by wongk711** [comment]
Meteor checklist: 
- Define, update, Remove methods are missing

**Comment by jcamarao** [comment]
METEOR-01: package still there
METEOR-02: package missing
METEOR-03: methods are very bare and not secure

**Comment by tiffanywilliams** [comment]
METEOR-01
	- insecure@1.0.7 in .meteor/packages

METEOR-02
	- Can't find mdg:validated-method

**Comment by Rexter-DS** [comment]
Architecture checklist

- camel casing

**Comment by yiwenc22** [comment]
METEOR-01: insecure package still added.
METEOR-02: package missing

**Comment by christianjensenv** [comment]
comments 8, 10, and 12 are not needed for design checklist

**Comment by patimapoochai** [comment]
L9: JS-01: Favourites what? food? owner? Should name it FavouriteFood.
.meteor/packages
L10: METEOR-01: mongo@1.10.0 is outdated, mongo uses new storage engine now

**Comment by s-rathyen** [comment]
ESLINT-01: Prefer default export. (import/prefer-default-export) Line 25

**Comment by tgabatin** [comment]
camel casing, archietcture define, update remove missing

**Comment by edwin-zheng** [comment]
METEOR-01 insecure package still there

METEOR-02 mdg:validated-method package may not be there

**Comment by bradenbetz** [comment]
remove lines 8, 10, 12 they seem redundant, METEOR-01 is insecure and METEOR-02 missing

**Comment by JiajunK** [comment]
comments are vague

**Comment by trey-sumida** [comment]
Arch-01: Obey file name conventions
"menuItem" directory should be named menu-item
"menuItem" file should be named MenuItem in app/imports/api/menuItem

METEOR-01: Remove the insecure package.
insecure package needs to be removed from .meteor/packages

METEOR-02: Add the mdg:validated-method package.
mdg:validated-method package needs to be added

METEOR-04: Use validated methods to update collections.
Need to add ValidatedMethods to define, update and remove documents from the Meteor collections.

**Comment by kyraikeda** [comment]
METEOR-01: insecure package still in .meteor/packages

METEOR-02: project does not have mdg:validated-method package

METEOR-03: Mongo collections are not wrapped in a class with define, update, removeIt methods

**Comment by CalianaFortin** [comment]
FavoriteCollection
Arch-03: The newly created directory is not consistent in location and meaning with other directories it should be either called FavoriteCollection or Favorites. Be specific with the type of favorites. 
METEOR-01: The insecure package has not been removed. 
METEOR-04: There are no Validated Methods to define, update and remove documents from the Meteor collections.

**Comment by justin-mar** [comment]
METEOR-01: Insecure package

METEOR-02: Missing the mdg:validated-method package.

**Comment by cammoore** [comment]
// Technical debt: delete comments on 8, 10, and 12.

**Comment by alohajerome** [comment]
Meteor-01: Need to remove insecure package.

Meteor-04: Need to use Validated Methods. So that we can define, update and remove documents/items from a Meteor collections
