### ISSUE TITLE
Review: imports/ui/pages/EditRestaurants.jsx

### ISSUE THREAD

**Issue by cammoore** [cammoore/campus-cravings#3]
## Overview

We'll be reviewing the AvailableRestaurants and EditRestaurants pages. 

Please focus on:
 * Javascript issues and
 * React component issues

## Review Branch

[review-3](https://github.com/cammoore/campus-cravings/tree/review-3)

## Files to review

(Please list the files to be reviewed here. It would be great to provide the URL to each file in the review branch.)

* [AvailableRestaurants.jsx](https://github.com/cammoore/campus-cravings/blob/review-3/app/imports/ui/pages/AvailableRestaurants.jsx)
* [EditRestaurants.jsx](https://github.com/cammoore/campus-cravings/blob/review-3/app/imports/ui/pages/EditRestaurants.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)

## Due date

Tuesday, Feb. 2nd at noon.

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by s-rathyen** [comment]
DESIGN-05: Inappropriate comments
EditRestaurants.jsx lines 64, 53
AvailableRestaurants.jsx lines 85, 93
“Get access to Stuff documents” & similar use of “Stuff”

JS-07: Avoid console.logs
AvailableRestaurants.jsx line 27
Console log

**Comment by patimapoochai** [comment]
AvailableRestaurants.jsx:
L18, L20: Design-01, same lines of code, just added i+1 and * 10
L18: Design-02?: double if's in a for loop

L31, 35, 42: Design-05: what does true means and false means? maybe also return error codes instead of falses?

L27, 58: JS-07: console.log's

EditRestaurants.jsx:
L11: Design-05: what does this line do? no comments

**Comment by edwin-zheng** [comment]
AvailableResources.jsx
JS-07: Lines 27, 58

ESLINT-01: Line 21, line length error

REACT-09: Line 47, can convert to function, no state used, only props

EditRestaurant.jsx
Design-05: Line 16, unecessary comment, the function name is describes the same thing
	          Line 64, Comment too general or unecessary.

ESLINT-01: Line 19, line length error
	          Line 70, new line at the end of document required

**Comment by cammoore** [comment]
AvailableRestraunts.jsx

JS-05: L9 Use arrow functions
JS-07: L27 avoid console.log
JS-08: L11, 15, 28, 28, 33, 37, 41, 46 etc. Avoid /** comments
REACT-06: L96 Define consts in withTracker
REACT-09: L47 Prefer functions vs. classes

EditRestraurants.jsx

Arch-01: File name This only edits a single restaurant.
REACT-09: L14 prefer functions vs. classes
JS-08: L16, 24, 29 Comments
REACT-06: L67 Define consts in withTracker

**Comment by JiajunK** [comment]
AvailableRestaurants.jsx
Line 85: /** Require an array of Stuff documents in the props. */, what is "stuff documents"?
EditRestaurants.jsx
Line 16: /** On successful submit, insert the data. */, what is "the data", might be helpful when comments are more specific

**Comment by angcylau** [comment]
AvailableRestaurants.jsx
L27, 58 : JS-07: Avoid console.logs
L46, 85, 93: JS-08: Comment does not appropriately describe code

EditRestaurants.jsx
L53, 64: JS-08: Comment does not appropriately describe code

**Comment by bradenbetz** [comment]
AvaliableResturants.jsx
ESLint: Unexpected console statement. (no-console) :27
ESLint: Unexpected console statement. (no-console) :58
 
Could fix the group of if statements from lines 30-44 & maybe the code at lines 18-20 seems a little bit chunky

**Comment by jackiewong99** [comment]
**AvailableRestaurants.js**

Line 17: Variable name should change as it is later used to store the restaurant hours rather than just a number

Line 27: Production code should not be logging any information to the console

Line 56: Variable name is not descriptive/meaningful

Line 58: Production code should not be logging any information to the console

Line 60: In the issue with the variable name in Line 56, the code does not read like English in this line.

**EditRestaurants.jsx**

Line 13: Should change “document” to “restaurant” in the comment

Line 53: Comment mentions the “Stuff” documents from the template rather than “Restaurants” documents

**Comment by annacampainha** [comment]
JSX files: 
ES Lint  errors
Comments are indirect and do not properly reflect the lines of code

**Comment by sophiaelizecruz** [comment]
AvailableRestaurants.jsx

JS-07: Avoid console.logs
- Line 27: Get rid of console.log.

JS-08: Use JSDoc comments appropriately.

Design-05: Ensure comments are appropriate.


EditRestaurants.jsx
- Design-05: Ensure comments are appropriate.

**Comment by timothyhuo1** [comment]
AvailableRestaurants.jsx
L9: JS-05: Could use arrow functions
L27, 58: JS-07: delete console.log statements
L9: JS-08: Add a comment 
L96: REACT-06: Define constants 
EditRestaurants.jsx
L29: JS-08: Comment not needed

**Comment by micgainey** [comment]
react-09: prefer functions vs classes for stateless components
eslint-01: console.logs
design-05: ensure comments are appropriate
js-08: use jsdoc comments appropriately

**Comment by yiwenc22** [comment]
AvaiableRestaurants.jsx
-Avoids using /** for comments JS-08

EditRestaurants.jsx
-some comment not needed(L29,L13) JS-08

**Comment by trey-sumida** [comment]
Design-05: Ensure comments are appropriate.
EditRestaurants.jsx:
L13:  comment is vague

JS-07: Avoid console.logs
AvailableRestaurants.jsx:
L27, 58: remove console.log

**Comment by alohajerome** [comment]
AvailableResources.jsx:
JS-08: L11, L15, L28, stop doing /** comments now
REACT-09: L47, maybe use functions 

EditRestaurants.jsx:
Couldn't find anything too significant but -
L11 - explain what this does

**Comment by kyraikeda** [comment]
**AvailableRestaurants.jsx**
JS-07: Avoid console.logs
Lines 27 and 58 have console.log statements

DS-05: Ensure comments are appropriate.
Line 46 is irrelevant to the actual code

**EditRestaurants.jsx**
DS-05: Ensure comments are appropriate
Line 53 is irrelevant

**Comment by jtmoka** [comment]
I could not find anything significant.

**Comment by saitoshi** [comment]
AvailableRestauraunts.jsx 
JS-07: Avoid console.log 

DS-05: Appropriate comments
Edit Restaurant 
DS-05: Appropriate comments
Line 53 Did not seem relevant

**Comment by mkirts** [comment]
Both:

Unnecessary console.log

EditRestaurants.jsx
DS-05: use appropriate comments

**Comment by chakhon** [comment]
AvaiableRestaurants.jsx
-JS-08: Avoids using /** for comments
-JS-07: Delete console.log statements

**Comment by tgabatin** [comment]
AvailableRestaurants.jsx
JS-07: Delete the console.log
Line 27/58: Console Log statement

EditRestaurants.jsx
Line 53: Not relevent

**Comment by dmestacio** [comment]
AvailableRestaurants.jsx

Design-05: L11, 57 seem unnecessary. 
Design-08: L18-23 repeated some lines.
JS-07: L27, 58 avoid ‘console.log’ statements
JS-08: L11, 29, 33, 37, 41 and 57, avoid /**
ESLINT-01: L67, 77 Typo: In word ‘availablerestaurants’; L27, 58 Unexpected console statement. 

EditRestaurants.jsx
ESLINT-02: L3 ESLint is picking up ‘swal’ as a typo error

**Comment by christianjensenv** [comment]
AvailableRestaurants.jsx
Dont need console logs

EditRestaurants.jsx
Not much wrong
line 13, use restaurant instead of document, 29 & 53 comments not needed

**Comment by nicholasmp** [comment]
Design-02: Deeply nested conditionals
	isOpen Function in AvailableRestaurants file contains a for and two if nested but not necessarily if/else blocks?

React-01: Components should be simple
	EditRestaurants could be broken up.

React-09: Prefer functions vs. classes for stateless components
	EditRestaurants uses a class instead of a function for its stateless components.

**Comment by christianjensenv** [comment]
> AvailableRestaurants.jsx
> Dont need console logs
> 
> EditRestaurants.jsx
> Not much wrong
> line 13, use restaurant instead of document, 29 & 53 comments not needed

-Sorry internet is down-

**Comment by tiffanywilliams** [comment]
AvailableRestaurants.jsx
______________________________

Design-01: Lines 66 to 74 are similar to lines 76 to 81 with only differences in lines 69 to 72 and 79. Could maybe use a ternary operator.

JS-05: Line 9. Could use arrow function for function 'isOpen'.

JS-07: Get rid of console.logs at lines 27 and 58. 

JS-08: Comments could use '//' instead of '/**'.



EditRestaurants.jsx
_____________________________

JS-08: Comments could use '//' instead of '/**'.

**Comment by Rexter-DS** [comment]
AvailableRestaurants.jsx

Architecture Checklist 
 - files are not using camel casing

Design Checklist
 - logic for isOpen feels repetitive/chunky

Javascript Checklist
 - stray console log
 - using jsdoc inappropriately

EditRestaurants

Architecture Checklist 
 - files are not using camel casing

**Comment by jklaulau** [comment]
AvailableRestraunts.jsx
JS-05: L9 Use arrow functions
JS-08: Avoid using comments with /**
EditRestraurants.jsx
DS-05: Unappropriated comments

**Comment by justin-mar** [comment]
AvailableRestaurants.jsx:
JS-05: line 9
JS-07: line 27, 58
JS-08: line 11, 15, 28, 29, 33, 37, 41, 49, 54, 57, 91

EditRestaurants.jsx:
JS-08: line 13, 16, 24, 29, 53, 60
REACT-06: line 67

**Comment by wongk711** [comment]
AvailableRestaurants.jsx

line 27 remove console.log
line 58 remove console.log

change comment type in lines 11-41, 49-91 to std instead of JSDoc (comment on line 46 is fine)

variable d needs renaming line 56

EditRestaurants.jsx

comment on 13 is okayish,
change comment type for the rest

const bridge should be defined in withTracker() line 11

**Comment by jcamarao** [comment]
Design
--------------
Design-05: Some of the comments seemed to be cut-and-paste and not modified for the new code (Both files)

Javascript
--------------
JS-07: There are still console.logs present in the code (AvailableRestaurants.jsx)
JS-08: Overuse of JSDoc (both files)

React
-------------
REACT-06: Constants weren't defined with withTracker() (both files)
REACT-09: should be stateless in certain portions (both files)

**Comment by lcaraang** [comment]
AvailableRestaurants:
L27, 58: JS-07: Avoid console.logs
L11, 15, etc. JS-08: Use JSDoc comments appropriately.

EditRestaurants:
L19: ESLINT-01: No errors, avoid warnings.
L16, 24, 29: JS-08: Use JSDoc comments appropriately.
