### ISSUE TITLE
Review:  Favorites.jsx and Footer.jsx

### ISSUE THREAD

**Issue by cammoore** [cammoore/campus-cravings#6]
## Overview

We are going to learn how to conduct an IDPM Review.

## Review Branch

[review-6](https://github.com/cammoore/campus-cravings/blob/review-6/)

## Files to review

* [Favorites.jsx](https://github.com/cammoore/campus-cravings/blob/review-6/app/imports/ui/components/Favorite.jsx)
* [Footer.jsx](https://github.com/cammoore/campus-cravings/blob/review-6/app/imports/ui/components/Footer.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)

## Due date

1/22

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s23/morea/review/reading-idpm-review.html

**Comment by cammoore** [comment]
## Favorites.jsx

AR-01: Filename is Favorites while the component is named Favorite.
JS-08: L6, L27, L33 Don't use /** comments
RE-09: L7 Prefer arrow functions.
L9, 10: Why rename the props?
L34 Don't need the withRouter there are no <Link> elements.

## Footer.jsx

JS-08: L3 /** comment. Is the comment correct?
RE-09: L4 Prefer arrow functions
L6 Do we need this const? It is only used once.

**Comment by colas002** [comment]
Favorites.jsx
Arch-01: File named Favorites but component named Favorite
Arch-01: RestaurantInfo did not use camel case
Design-05: Unnecessary comment /** Wrap this component in withRouter since we use the <Link> React Router element. */
REACT-09: Did not use arrow function

Footer.jsx
REACT-09: Did not use arrow function

**Comment by sanehirakenji** [comment]
Favorites.jsx
Design-05: L6: Comment refers to “List Stuff” table and “pages.ListStuff.jsx” which do not exist.
JS-01: L9: The “RestaurantInfo” variable should be “restaurantInfo” to use camelcase.
JS-08:  L27,33:  Both of these comments should not begin with “/**” as they are not JSDoc comments that define the Favorite component.
ESLINT-02: The ESLint error did not catch when the variable name was not camelcase appropriate.
REACT-04: This component could be worked on by destructuring better.

Footer.jsx
Design-01: There are no lines that look similar in this file. However, in line 6, there is an unnecessary variable declaration of the styling that is used in line 9.
JS-05: As this is a static immutable component, the whole class could be replaced by an arrow function.
REACT-09: This is a static immutable component and it can be replaced by a function.

**Comment by jgaleria** [comment]
## Favorites.jsx
DESIGN-05: Comment refers to "List Stuff" which doesn't exist
JS-01: Variable naming convention (RestaurantInfo vs menuItemInfo)
REACT-09: Can use arrow function to render web page

## Footer.jsx
REACT-09: Can use arrow function to render web page

**Comment by ian-lastname** [comment]
**Favorites.jsx**
AR-01: File name is Favorites.jsx but component name is Favorite.jsx
JS-01: Inconsistent casing between "RestaurantInfo" and "menuItemInfo"
RE-04: Could've used prop destructuring
RE-07: Data form restaurant and menuItem collections obtained within render

**Footer.jsx**
RE-09: Use arrow function instead

**Comment by tevin-takata** [comment]
## Favorites.jsx
REACT-09: L7 use arrow function
DESIGN-05: L6 Comment refers to pages/ListStuff.jsx, which does not exist

## Footer.jsx
REACT-09: L4 use arrow function

**Comment by josiahkila** [comment]
## Favorites.jsx

 **Arch-01: File named Favorites but component named Favorite**

 **ESLINT-02: Use camelcase appropriate.**

## Footer.jsx

 *REACT-09: use arrow function*

**Comment by silviadebenedictis** [comment]
### Favorites.jsx
Arch-01: File is named Favorites but component's name is Favorite
Design-05: Unnecessary comment about ListStuff
JS-08: L6, L27, L33 should not use /** comments

### Footer.jsx
React-09: L4 use arrow function

**Comment by UHMyafeiwang** [comment]
## Favorites.jsx
AR-01: File name is Favorites.jsx but component name is Favorite.jsx
Arch-01: RestaurantInfo should be camel case


## Footer.jsx
React-09: L4 use arrow function

**Comment by tylerz1443** [comment]
### Favorites.jsx
- JS-08: Uses /** comments for non documentation required information
- JS-08: Does not use arrows to do assignments 

### Footer.jsx
- JS-08: Uses /** comments for non documentation required information

**Comment by joelvanta** [comment]
### Favorites.jsx

- JS-08: Avoid ‘/**’ comments for L6, L27, L33
- React-09: L9 should use the arrow functions

### Footer.jsx

- React-09: L4 should use the arrow functions
- JS-08: L3 /** comment seem to be inappropriate.

**Comment by connorn-dev** [comment]
## Favorites.jsx
<br>
Arch-01: File name name is plural, component is singular (Favorites.jsx and Favorite.jsx). 

JS-01: L9: Variable "ResturantInfo" should use camel case ("resturantInfo"). 
Design-05: Comment is unnecesary. 
## Footer.jsx
<br>
RE-09: Should use arrow functions instead (ES6).

**Comment by hokwaichan** [comment]
**Favorites.jsx**
Arch-01: File named Favorites.jsx but component named Favorite.jsx
Design-05: Unnecessary comment "List Stuff"

**Footer.jsx**
 REACT-09: Use arrow functions

**Comment by Nicsteg** [comment]
## Favorites.jsx
AR-01: File is Favorites.jsx while the component is named Favorite.
REACT-08: component name is Favorite and doesn't match the file name Favorites.jsx
REACT-09: No arrow functions

## Footer.jsx
REACT-09: No arrow functions

**Comment by kairemUH** [comment]
## Favorites.jsx
JS-08: L6, L27, & L33: Inconsistent and odd commenting format.
JS-01: L9: Use camel case, as done on the line below.

## Footer.jsx
DESIGN-01 : L6 & L9: Unnecessary declaration of local variable that gets used once.
REACT-09: Arrow function preferred.

**Comment by juvyannl** [comment]
## Favorites.jsx
JS-01: Need to use camel case (restaurantInfo)
JS-08: L6, L27, L33 inappropriate /** comments

## Footer.jsx
RE-09: Needed arrow function

**Comment by micahtilton** [comment]
# Favorite.jsx
REACT-09: L7 - Prefer functions vs. classes for stateless components.
Design-05: L6 - Ensure comments are appropriate.
 - pages/ListStuff.jsx in comment should be renamed to pages/ListFavorites.jsx
# Footer.jsx
REACT-09: L4 - Prefer functions vs. classes for stateless components.

**Comment by jligeral** [comment]
## Favorite.jsx ##
JS-01: L9 RestaurantInfo needs to be camel case. This explains why the text is colored
Design-05: L6 Comment is referring to ListStuff.jsx currently. Change to 'Favorite'
REACT-09: L7 Component is stateless so just write as a function

## Footer.jsx ##
L8: 'bottom-footer' is a strange id name. If footer exists on every page, then '.footer' should suffice for css
REACT-09: Component is stateless so just write as a function
